model_list:
  - model_name: mistral-7b-instruct
    litellm_params:
      model: openrouter/mistralai/mistral-7b-instruct:free
      rpm: 60
  - model_name: mistral-7b-instruct
    litellm_params:
      model: huggingface/mistralai/Mistral-7B-Instruct-v0.2
      rpm: 60
  - model_name: mistral-8x7b
    litellm_params:
      model: groq/mixtral-8x7b-32768
      rpm: 60
  - model_name: Llama-2-7b
    litellm_params:
      model: cloudflare/@cf/meta/llama-2-7b-chat-fp16
      rpm: 60
  - model_name: claude-3-sonnet
    litellm_params:
      model: anthropic/claude-3-sonnet-20240229
      rpm: 60
  - model_name: claude-3-haiku
    litellm_params:
      model: anthropic/claude-3-haiku-20240307
      rpm: 60

      
litellm_settings:
  drop_params: True
  # max_budget: 100 
  # budget_duration: 30d
  num_retries: 5
  request_timeout: 600
  telemetry: False
  # context_window_fallbacks: [{"gpt-3.5-turbo": ["gpt-3.5-turbo-large"]}]

general_settings: 
  master_key: os.environ/MASTER_API_KEY
  proxy_budget_rescheduler_min_time: 60
  proxy_budget_rescheduler_max_time: 64
  proxy_batch_write_at: 1
  # database_url: "postgresql://<user>:<password>@<host>:<port>/<dbname>" # [OPTIONAL] use for token-based auth to proxy

# environment_variables:
  # settings for using redis caching
  # REDIS_HOST: redis-16337.c322.us-east-1-2.ec2.cloud.redislabs.com
  # REDIS_PORT: "16337"
  # REDIS_PASSWORD: 
